---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  http_port: "10080"
  https_port: "10443"
  test-index.html: |+
    <html><head>Test index</head>
    <body><h1>Test index</h1>
    <p>This is test index page, thanks for your visit</p>
    </body></html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  replicas: 1
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool:alpine-extra
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx
                  key: http_port
            - name: HTTPS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx
                  key: https_port
          volumeMounts:
            - name: html-root
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-root
          configMap:
            name: nginx
            items:
              - key: test-index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: multitool
spec:
  type: LoadBalancer
  ports:
    - name: multitool-http
      port: 10080
    - name: multitool-https
      port: 10443
  selector:
    app: multitool

