---
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod: pod-1
  name: pod-1
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pod-1
spec:
  ports:
    - name: web
      port: 80
  selector:
    pod: pod-1

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    pod: pod-2
  name: pod-2
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:alpine-extra
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pod-2
spec:
  ports:
    - name: web
      port: 80
  selector:
    pod: pod-2

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
spec:
  podSelector:
    matchLabels:
      pod: pod-2
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            pod: pod-1
      ports:
      - protocol: TCP
        port: 80
    - to:
        - ipBlock:
            cidr: 169.254.25.10/32
      ports:
        - protocol: UDP
          port: 53


